name: segregation
channels:
  - conda-forge
dependencies:
  - python >=3.12
  - geopandas
  - joblib
  - libpysal
  - mapclassify
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pyproj >=3
  - scikit-learn
  - scipy
  - statsmodels
  - seaborn
  - tqdm
  # docs (building the docs also executes the example notebooks)
  - sphinx
  - myst-nb
  - jupyter-cache
  - ipykernel
  - ipywidgets
  - numpydoc
  - sphinxcontrib-bibtex
  - sphinx_bootstrap_theme
