name: segregation
channels:
  - conda-forge
dependencies:
  - python >=3.12
  - geopandas
  - joblib
  - libpysal
  - mapclassify
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pyproj >=3
  - scikit-learn
  - scipy
  - seaborn
  - tqdm